spring:
  application:
    name: meslicence
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.255.128.84:15954/mes-licence?characterEncoding=utf8&useSSL=false
    username: root
    password: 123@456.coM
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 200
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-request-size: "30MB"
      max-file-size: "3MB"
  webservices:
    url: http://10.255.52.28:8802/QueryBasicInfor.asmx
  storage:
    file:
      ip: 7356198063231685.test.paas.gwm.cn
      port: 80
      bucketName: meswqnew
      userName: 1b8b432df2bfbd25
      password: 123.Com

server:
  port: 8090

#日志插件默认配置
gwmlog:
  #平台名称，必须全小写，不可以有特殊字符，请使用部门名称简写（如：ywztb）
  platformname: "ywztb"
  #项目名称，必须全小写，不可以有特殊字符（如：mes）
  projectname: gw
  default:
    #默认索引名称，必须全小写，不可以有特殊字符
    indexname: "default"
    #默认日志类型，必须全小写，不可以有特殊字符（如：info、debug、warn、exception、error）
    logtype: "debug"


#apollo:
#  meta:   #此处配置apollo地址
#  bootstrap:
#    enabled: true
#    eagerLoad:
#      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://10.255.29.31:8761/eureka/

feign:
  hystrix:
    enabled: true
  url:
    oauth: "http://oauthmanage.test.paas.gwm.cn"
    mdm: "http://mesbms.test.paas.gwm.cn"
    plan: "http://mesplan.test.paas.gwm.cn"
    eqp: "http://meseqp.test.paas.gwm.cn"

hystrix:
  default:
    coreSize: 50 #并发执行的最大线程数 50
    maxQueueSize: 200 #BlockingQueue的最大队列数 200
    queueSizeRejectionThreshold: 200 #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        timeout:
          enabled: true #执行是否启用超时
        isolation:
          thread:
            #hystrix超时时间的计算： (1 + MaxAutoRetries + MaxAutoRetriesNextServer) * ReadTimeout
            timeoutInMilliseconds: 3000  #命令执行超时时间 3秒
          semaphore:
            maxConcurrentRequests:  50 #最大并发请求数 50
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 50 #如果并发数达到该设置值，请求会被拒绝和抛出异常并且fallback不会被调用。50
    #配置具体方法超时时间  类名#方法名(入参类型)
#    UserService#usersById(Integer):
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000



ribbon:
  #ribbon 读取超时时长，默认5000  ribbonTimeout = (ReadTimeout + ConnectTimeout) * (maxAutoRetries + 1) * (maxAutoRetriesNextServer + 1);
  ReadTimeout: 5000
  retryableStatusCodes: 404,405,500

  #是否所有操作都重试,设置为false时，只会对get请求进行重试。设置为true,对所有的请求进行重试。
  #如果设置为true,put或post等写操作，必须做做幂等性验证
  OkToRetryOnAllOperations: false

  #负载均衡规则,过滤掉那些因为一直连接失败的
  #被标记为circuit tripped的后端server，
  #并过滤掉那些高并发的的后端
  #server（active connections 超过配置的阈值）
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.AvailabilityFilteringRule #AvailabilityFilteringRule
  eureka:
    enabled: true

mybatis:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  configuration:
    #开启驼峰命名转换
    map-underscore-to-camel-case: true
    #打印sql信息
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#暴露全部的监控信息
management:
 endpoints:
    web:
      exposure:
        include: "*"
 endpoint:
    health:
      show-details: ALWAYS


#antMatchers为：放开某个具体请求的接口
#regexMatchers：放开某个路径下所有的请求
path:
  antMatchers:
    #- "/**"
    - "/login/**"
    - "/amsusers/findResources"
    #- "/**"
    - "/wqpdfoperation/seePdfOnly"
  regexMatchers:
    - ".*swagger.*"
    - ".*doc.*"
    - ".*v2.*"
    - ".*vcpqualifiedcertconfigsequence.*"
    - ".*vcpqualifiedcerttemplate.*"
    - ".*html.*"
    - ".*webjars.*"


wq:
  reportStart: XC
  token:
    url: https://xcxx.vecc.org.cn/w/WSNewCar/login
    username: CebNYm00061111111111
    password: Bddq22661
  uploadUrl: https://xcxx.vecc.org.cn/w/WSNewCar/uploadofflinetest
  selectDataUrl: https://xcxx.vecc.org.cn/w/WSNewCar/list
  selectNumUrl: https://xcxx.vecc.org.cn/w/appearLog/queryAppNum
  reportCodeUrl: http://10.255.30.41:8080/wqTestReportCode/getCode
  #  reportTemplate: D:\mes_workspace\mes_credentials\scm-gmes\scm-gmes-starter\src\main\resources\static\jaspers\TestReportQY.jrxml
  reportTemplate_jrxml_qy: wq/TestReportQY.jrxml
  reportTemplate_jrxml_cy: wq/TestReportCY.jrxml
  reportTemplate_sub_jrxml_qy: wq/ReportModules.jrxml
  reportTemplate_sub_jrxml_cy: wq/ReportModulesCY.jrxml
  chapter: /wq/GW_SEAL_PH.PNG
  qcImage: /wq/GW_TESTING.PNG

mes:
  factory:
    code: "D410"
    workshopCode: "F"

oppenoffice:
  connectIp: 10.255.30.210
  connectPort: 29994